---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Volumes/Macintosh SSD partition/jellyfin_library:/config
      - /Volumes/Macintosh SSD partition/series:/data/tvshows
      - /Volumes/Macintosh SSD partition/peliculas:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped